version: '3'
services:
  benchmarkworker:
    container_name: benchmarkworker
    image: benchmarkworker
    # Restart this container until everything comes up, since some of the other services might not be ready yet
    restart: on-failure
    build:
        context: .
        dockerfile: BenchmarkWorker/Dockerfile
    environment:
      - Kafka__BootstrapServers=kafka-broker:9092
      - Kafka__SchemaRegistryUrl=schema-registry:8081

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
        - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka-broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
    - KAFKA_AUTO_CREATE_TOPICS_ENABLED="true"
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  schema-registry:
    container_name: schema-registry
    hostname: schema-registry
    image: confluentinc/cp-schema-registry:6.2.0
    restart: always
    depends_on:
      - zookeeper
    environment:
    - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-broker:9092
    - SCHEMA_REGISTRY_HOST_NAME=schema-registry
    - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081 
    - SCHEMA_REGISTRY_DEBUG=true
    ports:
      - 8081:8081
